dataset: 2D ADNI T1
data loading:
  attributes:
  - age
  - baseline diagnosis
  - MMSE
  - CDR
  image shape:
  - 224
<<<<<<< HEAD
  - 160
paths:
  # nii dir: /data/vision/polina/scratch/clintonw/datasets/ADNI/affine
  # FLAIR nii dir: /data/vision/polina/projects/wmh/incoming/2018_10_02/ADNI
  metadata: /data/vision/polina/projects/wmh/clintonw/tables/ADNI/adni_t2flair_10_02_2018.csv
  data root: /data/vision/polina/scratch/clintonw/datasets/ADNI
  3D T1 npy subdir: t1/npy
  2D T1 npy subdir: 2d_t1
=======
  - 160
>>>>>>> 05210ec13073bcca9b4dbff798fb626d963082dc
