network:
  type: IPGAN
  generator:
    min channels: 16
  discriminator:
    type: DenseNet
data loading:
  batch size: 8
  spread: 1.2
loss:
  adversarial loss type: WGAN-GP
  ID loss: .1
  reconstruction loss: .01
  diff loss: 10.
  gradient penalty: .1
optimizer:
  G learning rate: 5e-5
  D learning rate: 1e-5
  weight decay: 1e-4