network:
  type: IPGAN
  generator:
    min channels: 16
  discriminator:
    type: simple
    pretrained: False
data loading:
  batch size: 6
  spread: 1.2
loss:
  adversarial loss type: WGAN-GP
  ID loss: .1
  reconstruction loss: 1
  diff loss: 1.
  gradient penalty: 1
optimizer:
  D learning rate: 1e-4
