dataset: 2D MRI-GENIE FLAIR
data loading:
  attributes:
  - age
  - NIHSS
  image shape:
  - 224
  - 192
paths:
  data root: /data/vision/polina/scratch/clintonw/datasets/MRI-GENIE
  GASROS:
    3D npy subdir: gasros_flair/correct_bias_field
    2D npy subdir: 2d_gasros/npy
  MRI-GENIE:
    3D npy subdir: mrigenie_flair/rescale_and_register
    2D npy subdir: 2d_mrigenie/npy
