network:
  type: RGAE
  generator:
    type: UNet
    res blocks: 1
    min channels: 16
  regressor:
    type: simple
    pretrained: False
data loading:
  batch size: 8
loss:
  reconstruction loss: .1
optimizer:
  epochs: 30
  R learning rate: 1e-3
