network:
  type: StarGAN
  discriminator:
    type: simple
    pretrained: False
  generator:
    type: UNet
    min channels: 16
    optimizer step interval: 1
    res blocks: 1
loss:
  adversarial loss type: WGAN-GP
  attribute loss: 10
  reconstruction loss: .1
  regressor loss: 10
  gradient penalty: 1
optimizer:
  D/R learning rate: 1e-3
