optimizer:
  G learning rate: 1e-4
  D/R learning rate: 2e-5
data loading:
  spread: 1.5
loss:
  attribute loss: 100.
  reconstruction loss: .1
  regressor loss: 10
  adversarial loss type: WGAN-GP
  gradient penalty: .1
network:
  type: StarGAN
  discriminator:
    type: DenseNet
    pretrained: True
    # patch-based: true
    # min channels: 18
    # C/:
    #   bias: false
    #   kernel size: 3
    # down blocks: 5
    # downsampling type: strided conv
    # dropout: 0.0
  generator:
    optimizer step interval: 1
    res blocks: 4
    min channels: 24
    # initial kernel: 5
  # image activation: tanh
  # layer activation: leaky ReLU
