network:
  type: StarGAN
  discriminator:
    type: simple
    pretrained: False
  generator:
    type: AE
    optimizer step interval: 1
    res blocks: 1
    min channels: 16
data loading:
  batch size: 8
loss:
  adversarial loss type: WGAN-GP
  attribute loss: 100
  reconstruction loss: .01
  regressor loss: 10
  gradient penalty: 1
optimizer:
  D/R learning rate: 1e-3
